/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class main_java_com_example_physics_PhysicsEngine */

#ifndef _Included_main_java_com_example_physics_PhysicsEngine
#define _Included_main_java_com_example_physics_PhysicsEngine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     main_java_com_example_physics_PhysicsEngine
 * Method:    initPhysics
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_main_java_com_example_physics_PhysicsEngine_initPhysics
  (JNIEnv *, jobject);

/*
 * Class:     main_java_com_example_physics_PhysicsEngine
 * Method:    cleanupPhysics
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_main_java_com_example_physics_PhysicsEngine_cleanupPhysics
  (JNIEnv *, jobject);

/*
 * Class:     main_java_com_example_physics_PhysicsEngine
 * Method:    updatePhysics
 * Signature: (F)[F
 */
JNIEXPORT jfloatArray JNICALL Java_main_java_com_example_physics_PhysicsEngine_updatePhysics
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     main_java_com_example_physics_PhysicsEngine
 * Method:    updatePlayerPhysics
 * Signature: (FFFFFFF)[F
 */
JNIEXPORT jfloatArray JNICALL Java_main_java_com_example_physics_PhysicsEngine_updatePlayerPhysics
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     main_java_com_example_physics_PhysicsEngine
 * Method:    checkCollision
 * Signature: (FFF)Z
 */
JNIEXPORT jboolean JNICALL Java_main_java_com_example_physics_PhysicsEngine_checkCollision
  (JNIEnv *, jobject, jfloat, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
